### ISSUE TITLE
Bottles fails to start

### ISSUE THREAD

**Issue by 413Michele** [mirkobrombin/Bottles#10] opened 2017-10-17 18:00 UTC
Bottles fails to start, when I execute it from the terminal it gives me this error:

`com.github.mirkobrombin.bottles 
Traceback (most recent call last):
  File "/usr/local/bin/com.github.mirkobrombin.bottles", line 35, in <module>
    from bottles import main
  File "/usr/local/bin/bottles/main.py", line 27, in <module>
    import window as wn
  File "/usr/local/bin/bottles/window.py", line 27, in <module>
    import headerbar as hb
  File "/usr/local/bin/bottles/headerbar.py", line 27, in <module>
    import wine as w
  File "/usr/local/bin/bottles/wine.py", line 158, in <module>
    class Wine:
  File "/usr/local/bin/bottles/wine.py", line 162, in Wine
    wine_icon = Gtk.IconTheme.get_default().load_icon("wine", 16, 0)
GLib.Error: gtk-icon-theme-error-quark: Icona «wine» non presente nel tema elementary (0)
`

I am using wine-devel through the official wine repository (NOT the Ubuntu/elementary repo), I am not sure what the [wiki](https://github.com/mirkobrombin/Bottles/wiki/Why-can't-choose-the-version%3F) means in term of compatibility, but anyway the program shouldn't crash

Note that, even if I don't think it matters in this case, I have manually updated the kernel and am using an external repository for my graphics drivers (nvidia)

**Comment by mirkobrombin** [comment] 2017-10-17 18:14
It's not really a bug, I need to add a check. 
The problem is that it does not find the icon from the elementary dir, I have to provide it in the installation. 
I should also add support to the devel version of wine.

Thanks for the report I will fix it as soon as possible. With .deb should not be problems.

**Comment by danrabbit** [comment] 2017-10-18 18:20
I'm getting the same error from the packaged version. It doesn't seem like your packaging actually pulls in WINE as a runtime dependency

**Comment by mirkobrombin** [comment] 2017-10-18 20:30
Proposed solution in [release 0.0.3](https://github.com/mirkobrombin/Bottles/releases/tag/0.0.3)

**Comment by danrabbit** [comment] 2017-10-18 20:34
Right so you have two different types of dependencies. One is `Build-Depends` which are the packages that you need at build time (in liftoff) and another is `Depends` which are your runtime dependencies, which is the packages that a user needs to have installed on their system in order to use your app. So what you need to do is add wine (and anything else your package depends on) to your runtime dependencies, not your build dependencies.

**Comment by mirkobrombin** [comment] 2017-10-18 20:36
I do not want to go wrong but is not already set in that way?

**Comment by davidmhewitt** [comment] 2017-10-18 20:55
Hi @mirkobrombin ,

If you want bottles to depend on wine and pull it in when users install bottles, you need `wine` instead of `${wine:Depends}` in your `Depends` section.

The `${misc:Depends}, ${shlibs:Depends}` variables are special ones generated by the debian packaging system. Everything else should just be plain package names, like how `python3` is written.

**Comment by mirkobrombin** [comment] 2017-10-18 20:59
@davidmhewitt So now I should have fixed in [0.0.4](https://github.com/mirkobrombin/Bottles/releases/tag/0.0.4)

**Comment by danrabbit** [comment] 2017-10-19 00:37
Looks like this is solved in the latest packaging :+1:

**Closed** 2017-10-19 05:11 UTC
Labels: bug, waiting response
